version: '3'

services:
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    volumes: 
      - ./client:/usr/src/client
      - node_modules:/usr/src/client/node_modules
    command: npm start

  server:
    container_name: server
    build: ./server
    ports:
      - 3001:3000
    volumes:
      - ./server:/usr/src/server
      - node_modules_b:/usr/src/server/node_modules
    command: npm start

volumes: 
  node_modules:
  node_modules_b: